{% set name = "here-location-services" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/here-location-services-{{ version }}.tar.gz
  sha256: 10523492f15e688e20b13763793171511c7fdfb9e44daef52774644cd6cbe7fb

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - geojson
    - python >={{ python_min }}
    - requests
    - flexpolyline
    - pandas
    - pyhocon
    - requests-oauthlib

test:
  imports:
    - here_location_services
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://here.com
  summary: HERE Location Services for Python
  dev_url: https://github.com/heremaps/here-location-services-python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sackh
